name: secret-storing
on:
        push:
jobs:
        use-secret:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout Code
                          uses: actions/checkout@v6

                        - name: Display Secret Templates
                          run: echo "The secret is ${{ secrets.SECRET }}"

