name: secret-storing

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Secret Safely
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          echo "$SECRET" > /dev/null

      - name: Display Secret Template
        run: echo "The secret is \${{ secrets.SECRET }}"
