name: secret-storing
on:
        push:
jobs:
        use-secret:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout Code
                          uses: actions/checkout@v4

                        - name: Safely Use Secret
                          env:
                                SECRET: ${{ secrets.SECRET }}
                          run: |
                                echo "Secret loaded successfully"

                        - name: Display Secret Templates
                          run: echo "The secret is \${{ secrets.SECRET }}"

